// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-LjpwjDlUIRvF8Aa8hdWD9MlU0RD-AU',
    appId: '1:39751371043:web:ccd5884b372794ba516496',
    messagingSenderId: '39751371043',
    projectId: 'ecoflow-adbd3',
    authDomain: 'ecoflow-adbd3.firebaseapp.com',
    storageBucket: 'ecoflow-adbd3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_r7Y47z3rdSnq9hV1t_VFUFQOx5cSDJg',
    appId: '1:39751371043:android:fd31c1aa55557a8e516496',
    messagingSenderId: '39751371043',
    projectId: 'ecoflow-adbd3',
    storageBucket: 'ecoflow-adbd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlrvqmZYKNuXMISo8qCxyLaqL3J7Zja2g',
    appId: '1:39751371043:ios:a3112c5e656b71ec516496',
    messagingSenderId: '39751371043',
    projectId: 'ecoflow-adbd3',
    storageBucket: 'ecoflow-adbd3.appspot.com',
    iosClientId: '39751371043-88c223ps0kufr8rkkdv0padsfq9f6etu.apps.googleusercontent.com',
    iosBundleId: 'com.ecoflow.app.ecoflowV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlrvqmZYKNuXMISo8qCxyLaqL3J7Zja2g',
    appId: '1:39751371043:ios:a3112c5e656b71ec516496',
    messagingSenderId: '39751371043',
    projectId: 'ecoflow-adbd3',
    storageBucket: 'ecoflow-adbd3.appspot.com',
    iosClientId: '39751371043-88c223ps0kufr8rkkdv0padsfq9f6etu.apps.googleusercontent.com',
    iosBundleId: 'com.ecoflow.app.ecoflowV3',
  );
}
